import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import {
  ClerkProvider,

} from '@clerk/nextjs';
import FloatingButton from '@/components/FloatingButton';

import categories from './categories/Categories';
import SidebarLayout from './components/SidebarLayout';
import { CityProvider } from './context/CityContext';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "AI-PAT",
  description: "Generated by Ahmed Alaa",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <CityProvider>
            <SidebarLayout categories={categories}>
              {children}
            </SidebarLayout>
          </CityProvider>
          <FloatingButton />
          <Toaster />
        </body>
      </html>
    </ClerkProvider>
  );
}
